name: Build Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_windows:
    name: Build Windows (64 bit)
    runs-on: windows-latest

    steps:
      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: jurplel/install-qt-action@v2

      - name: Build
        env:
          TARGET_PLATFORM: windows
        run: |
          qmake OpenCLCapsViewer.pro
          nmake release
          windeployqt.exe release --no-opengl-sw --no-angle --no-webkit2 --no-translations --no-system-d3d-compiler
          Remove-Item release\*.obj
          Remove-Item release\*.res
          Compress-Archive -Path release\ -DestinationPath OpenCL_Caps_Viewer-windows.zip
      # - name: Upload
      #   if: github.ref == 'refs/heads/master'
      #   run: curl -T Vulkan_Caps_Viewer-windows.zip  ftp://${{ secrets.FTP_USER_NAME }}:${{ secrets.FTP_PASS }}@${{ secrets.FTP_SERVER_NAME }}