name: Build Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_windows:
    name: Build Windows (64 bit)
    runs-on: windows-latest

    steps:
      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: jurplel/install-qt-action@v2

      - name: Build
        env:
          TARGET_PLATFORM: windows
        run: |
          qmake OpenCLCapsViewer.pro
          nmake release
          windeployqt.exe release --no-opengl-sw --no-angle --no-webkit2 --no-translations --no-system-d3d-compiler
          Remove-Item release\*.obj
          Remove-Item release\*.res
          Compress-Archive -Path release\ -DestinationPath OpenCL_Caps_Viewer-windows.zip

      - name: Upload
        if: github.ref == 'refs/heads/master'
        run: curl -T OpenCL_Caps_Viewer-windows.zip  ftp://${{ secrets.FTP_USER_NAME }}:${{ secrets.FTP_PASS }}@${{ secrets.FTP_SERVER_NAME }}

  build_ubuntu:
    name: Build Ubuntu (X11)
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.12.9
          host: linux

      - name: Install OpenCL ICD loader
        run: |
          sudo apt update
          sudo apt install ocl-icd-opencl-dev

      - name: Build
        env:
          TARGET_PLATFORM: X11
        run: |
          echo ${TARGET_PLATFORM}
          PATH="/opt/qt512/bin:$PATH"
          CXX="clang++"
          qmake DEFINES+=X11 CONFIG+=release PREFIX=/usr
          make INSTALL_ROOT=appdir install ; find appdir/
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          export VERSION=${TARGET_PLATFORM}
          cp openclCapsViewer.png appdir/usr/share/icons/hicolor/256x256/apps/openclCapsViewer.png
          mv appdir/opt/OpenCLCapsViewer appdir/usr/share/OpenCLCapsViewer
          ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/* -appimage

      - name: Upload
        if: github.ref == 'refs/heads/master'
        run: curl -T OpenCL_Caps_Viewer-X11-x86_64.AppImage ftp://${{ secrets.FTP_USER_NAME }}:${{ secrets.FTP_PASS }}@${{ secrets.FTP_SERVER_NAME }}

  build_android:
    name: Build Android
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.12.9
          target: android
          arch: android_arm64_v8a 

      - name: Build
        env:
          TARGET_PLATFORM: ANDROID
        run: |
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
          qmake OpenCLCapsViewer.pro
          make install INSTALL_ROOT=/home/runner/work/OpenCLCapsViewer/OpenCLCapsViewer/
          androiddeployqt --input /home/runner/work/OpenCLCapsViewer/OpenCLCapsViewer/android-libOpenCLCapsViewer.so-deployment-settings.json --output . --android-platform android-30 --gradle

      - name: Upload
        # if: github.ref == 'refs/heads/master'
        run: curl -T /home/runner/work/OpenCLCapsViewer/OpenCLCapsViewer//build/outputs/apk/debug/OpenCLCapsViewer-debug.apk ftp://${{ secrets.FTP_USER_NAME }}:${{ secrets.FTP_PASS }}@${{ secrets.FTP_SERVER_NAME }}